typography_spectrum: 1
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b2855c'
    - '#005d90'
    - '#d42d01'
  brandStrength: 0.5898920097388327
  lightness: 0.2081912998110056
  saturation: 0.4371218776796013
  rhythmicContrast: 0.524949814658612
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.0073
analytics:
  google: null
  facebook: null
  twitter: null
name: GridWhat
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Hello There
description: Greetings from the Grid
purpose: []
