name: GridWhat
favicon: null
layout_spectrum: 0.58748
typography_spectrum: 0.57347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5898920097388327
  lightness: 0.2081912998110056
  saturation: 0.4371218776796013
  rhythmicContrast: 0.524949814658612
purpose: []
